### PR TITLE
Update gendev-macos to latest gendev and sgdk

### PR DESCRIPTION
**Pull request by matt456**
Hi,

Thanks for your great work on gendev-macos :-) I've just updated it to include all the latest changes from gendev and sgdk from when you first did it.

Everything seems to work great from some testing here. My mac is running the latest version of El Capitan.

Cheers,
Matt

### CODE REVIEW

**Comment by SONIC3D** [comment]
Thank you very much. =P

I will check it when I can touch my laptop,in a day or two.


On Mon, Jan 4, 2016 at 7:56 PM, matt456 <notifications@github.com> wrote:

> Hi,
>
> Thanks for your great work on gendev-macos :-) I've just updated it to
> include all the latest changes from gendev and sgdk from when you first did
> it.
>
> Everything seems to work great from some testing here. My mac is running
> the latest version of El Capitan.
>
> Cheers,
> Matt
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/SONIC3D/gendev-macos/pull/1
> Commit Summary
>
>    - Update gendev OSX to latest version of gendev (and SGDK)
>    - Fix skeleton files for OSX building
>
> File Changes
>
>    - *M* .gitignore
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-0> (1)
>    - *M* Makefile
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-1> (288)
>    - *A* README
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-2> (91)
>    - *R* files/Hex2bin-1.0.10.tar.bz2
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-3> (0)
>    - *R* files/VGMTools_src.zip
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-4> (0)
>    - *R* files/bin2c-1.0.zip
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-5> (0)
>    - *A* files/binutils-2.24.tar.bz2
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-6> (0)
>    - *A* files/gcc-4.8.2.tar.bz2
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-7> (0)
>    - *A* files/gmp-5.0.5.tar.bz2
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-8> (0)
>    - *M* files/makefile-gen.diff
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-9> (2)
>    - *A* files/mpc-0.8.2.tar.gz
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-10> (0)
>    - *A* files/mpfr-2.4.2.tar.bz2
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-11> (0)
>    - *A* files/newlib-1.19.0.tar.gz
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-12> (0)
>    - *R* files/sixpack-13.zip
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-13> (0)
>    - *R* files/sjasm39g6.zip
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-14> (0)
>    - *R* files/zasm-3.0.21-i386-osx10.6-2012-04-08.zip
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-15> (0)
>    - *R* files/zasm-3.0.21-source-linux-2011-06-19.zip
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-16> (0)
>    - *A* gen_gcc/makefile-gen
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-17> (162)
>    - *A* gen_gcc/makefile-gen-no-m68k-c++
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-18> (159)
>    - *A* gen_gcc/mars-myth-sdram.ld
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-19> (120)
>    - *A* gen_gcc/mars.ld
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-20> (120)
>    - *A* gen_gcc/md-myth-psram.ld
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-21> (114)
>    - *A* gen_gcc/md-myth-wram.ld
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-22> (117)
>    - *A* gen_gcc/md-split-ram.ld
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-23> (116)
>    - *A* gen_gcc/md.ld
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-24> (116)
>    - *D* pkg/DEBIAN/postinst
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-25> (7)
>    - *M* sgdk/Makefile
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-26> (29)
>    - *M* sgdk/files/Makefile.sgdk_lib
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-27> (19)
>    - *M* sgdk/files/Makefile.xgmtool
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-28> (10)
>    - *M* sgdk/skeleton/Makefile
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-29> (49)
>    - *M* sgdk/skeleton/boot/sega.s
>    <https://github.com/SONIC3D/gendev-macos/pull/1/files#diff-30> (51)
>
> Patch Links:
>
>    - https://github.com/SONIC3D/gendev-macos/pull/1.patch
>    - https://github.com/SONIC3D/gendev-macos/pull/1.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SONIC3D/gendev-macos/pull/1>.
>



-- 
A hedgehog who can not run fast...
:)

**Comment by matt456** [comment]
No problem, it was really straight forward to update :-)

I think potentially in the future it could all be modified to a script that pulls in the git latest of gendev and then diff's a few changes for osx.

**Comment by SONIC3D** [comment]
Hi,matt.Sorry for the slow reaction on this pull request.I finally get spare time on this hoppy project these days.And decide to fix the unsolved problem in this toolchain build.Including the vgm_cmp in VGMTool and sixpack.

So I would merge your pull request first before making additional changes.I have checked all difference in your commit.It seems all ok.Except one problem,that I found your pull request contains 6 archives that can be gathered from gnu.org.And their size is rather not small.I prefer to keep this repository as small as possible.So I have only put files that hosted on non-stable site locally in this repo.And I tried to keep the contribution credits in log so I hope you will recreate the pull request and remove these files from the commit:

binutils-2.24.tar.bz2
gcc-4.8.2.tar.bz2
gmp-5.0.5.tar.bz2
mpc-0.8.2.tar.bz2
mpfr-2.4.2.tar.bz2
newlib-1.19.0.tar.bz2

And yes,I plan to merge this repo to the gendev main repo of yours.But I need to solve the exist problem first.The problem of vgm_cmp in VGMTool is solved this afternoon.But the sixpack requires a little more works.The 3rd party aPLib used in this tool can not be built directly on Mac OS X.So after all these peripheral problems solved.I will make pull request to the main gendev repo with minimal changes,and integrate this toolchain.

**Comment by matt456** [comment]
I've made the changes to my fork and I think the pull request seems to have auto connected to the right commit after my rebase. I also merged in a very minor one line fix to the skeleton makefile.

Be great to revisit this when I have more time  :-D any problems just ask and I'll fix up.

**Comment by matt456** [comment]
Hi did you you have a any luck with this? I'd be interested to get hold of your VGM and sixpack fixes. I'm thinking of trying with the latest SGDK.

Cheers,
Matt

**Pull request merged**
