### PR TITLE
Update content to gendev version 0.3.0

### PR DESCRIPTION
**Pull request by v4ld3r5**
Hi,
Realized recently (July 8th 2017), kubilus1 performed an upgrade/cleanup of the gendev project, but there wasn't any activity on gendev-macos since last year. This PR contains changes up to date (as of 8th Aug); I've copied back the new folder structure and makefiles content from gendev, by keeping the changes needed for MacOS.

I've successfully build it on my mac running Sierra and xode cmdline tools versions:
```
mba13-dv:gendev-macos danielv$ xcode-select -v
xcode-select version 2347.
mba13-dv:gendev-macos danielv$
mba13-dv:gendev-macos danielv$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Best regards,
Dani

### CODE REVIEW

**Comment by WedgeSparda** [comment]
Hi. Doesn't seem that this PR is going to merged anytime soon. Using your repository https://github.com/v4ld3r5/gendev-macos we'll have the same result, right?

**Comment by v4ld3r5** [comment]
Hola! @WedgeSparda 
Give it a try, I was able to build basic "games" like the "Hello World" without issue, using the toolchain generated after those modifications

Un saludo / Regards

**Comment by SONIC3D** [comment]
Really sorry, I found I missed this pull request. I will check and merge it tomorrow afternoon or on Monday. And thank you very much! @v4ld3r5

**Comment by SONIC3D** [comment]
Seems there is no problem with XCode 8.x command line dev tools.
I'll test if it's all ok under XCode 9.x environment tonight.

Thanks, @v4ld3r5

**Comment by v4ld3r5** [comment]
hi,
great! a pleasure

Best regards

**Pull request merged**
